// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

// Protobuf Java Version: 3.25.1
package com.xzccc.netty.model.msg;

public final class ProtoMsg {
  private ProtoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code HeadType}
   */
  public enum HeadType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *登陆请求
     * </pre>
     *
     * <code>LOGIN_REQUEST = 0;</code>
     */
    LOGIN_REQUEST(0),
    /**
     * <pre>
     *登录响应
     * </pre>
     *
     * <code>LOGIN_RESPONSE = 1;</code>
     */
    LOGIN_RESPONSE(1),
    /**
     * <pre>
     *退出请求
     * </pre>
     *
     * <code>LOGOUT_REQUEST = 2;</code>
     */
    LOGOUT_REQUEST(2),
    /**
     * <code>LOGOUT_RESPONSE = 3;</code>
     */
    LOGOUT_RESPONSE(3),
    /**
     * <pre>
     *心跳请求PING;
     * </pre>
     *
     * <code>KEEPALIVE_REQUEST = 4;</code>
     */
    KEEPALIVE_REQUEST(4),
    /**
     * <code>KEEPALIVE_RESPONSE = 5;</code>
     */
    KEEPALIVE_RESPONSE(5),
    /**
     * <pre>
     *消息请求;
     * </pre>
     *
     * <code>MESSAGE_REQUEST = 6;</code>
     */
    MESSAGE_REQUEST(6),
    /**
     * <pre>
     *消息回执;
     * </pre>
     *
     * <code>MESSAGE_RESPONSE = 7;</code>
     */
    MESSAGE_RESPONSE(7),
    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * <code>MESSAGE_NOTIFICATION = 8;</code>
     */
    MESSAGE_NOTIFICATION(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *登陆请求
     * </pre>
     *
     * <code>LOGIN_REQUEST = 0;</code>
     */
    public static final int LOGIN_REQUEST_VALUE = 0;
    /**
     * <pre>
     *登录响应
     * </pre>
     *
     * <code>LOGIN_RESPONSE = 1;</code>
     */
    public static final int LOGIN_RESPONSE_VALUE = 1;
    /**
     * <pre>
     *退出请求
     * </pre>
     *
     * <code>LOGOUT_REQUEST = 2;</code>
     */
    public static final int LOGOUT_REQUEST_VALUE = 2;
    /**
     * <code>LOGOUT_RESPONSE = 3;</code>
     */
    public static final int LOGOUT_RESPONSE_VALUE = 3;
    /**
     * <pre>
     *心跳请求PING;
     * </pre>
     *
     * <code>KEEPALIVE_REQUEST = 4;</code>
     */
    public static final int KEEPALIVE_REQUEST_VALUE = 4;
    /**
     * <code>KEEPALIVE_RESPONSE = 5;</code>
     */
    public static final int KEEPALIVE_RESPONSE_VALUE = 5;
    /**
     * <pre>
     *消息请求;
     * </pre>
     *
     * <code>MESSAGE_REQUEST = 6;</code>
     */
    public static final int MESSAGE_REQUEST_VALUE = 6;
    /**
     * <pre>
     *消息回执;
     * </pre>
     *
     * <code>MESSAGE_RESPONSE = 7;</code>
     */
    public static final int MESSAGE_RESPONSE_VALUE = 7;
    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * <code>MESSAGE_NOTIFICATION = 8;</code>
     */
    public static final int MESSAGE_NOTIFICATION_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HeadType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static HeadType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN_REQUEST;
        case 1: return LOGIN_RESPONSE;
        case 2: return LOGOUT_REQUEST;
        case 3: return LOGOUT_RESPONSE;
        case 4: return KEEPALIVE_REQUEST;
        case 5: return KEEPALIVE_RESPONSE;
        case 6: return MESSAGE_REQUEST;
        case 7: return MESSAGE_RESPONSE;
        case 8: return MESSAGE_NOTIFICATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HeadType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HeadType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HeadType>() {
            public HeadType findValueByNumber(int number) {
              return HeadType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtoMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final HeadType[] VALUES = values();

    public static HeadType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HeadType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:HeadType)
  }

  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code LoginRequest}
   */
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginRequest)
      LoginRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequest() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsg.internal_static_LoginRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsg.internal_static_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoMsg.LoginRequest.class, ProtoMsg.LoginRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_ = 0L;
    /**
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoMsg.LoginRequest)) {
        return super.equals(obj);
      }
      ProtoMsg.LoginRequest other = (ProtoMsg.LoginRequest) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoMsg.LoginRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.LoginRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMsg.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProtoMsg.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ProtoMsg.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoMsg.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMsg.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoMsg.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginRequest)
        ProtoMsg.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsg.internal_static_LoginRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsg.internal_static_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoMsg.LoginRequest.class, ProtoMsg.LoginRequest.Builder.class);
      }

      // Construct using com.xzccc.netty_server.model.msg.ProtoMsg.LoginRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0L;
        token_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsg.internal_static_LoginRequest_descriptor;
      }

      @java.lang.Override
      public ProtoMsg.LoginRequest getDefaultInstanceForType() {
        return ProtoMsg.LoginRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoMsg.LoginRequest build() {
        ProtoMsg.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoMsg.LoginRequest buildPartial() {
        ProtoMsg.LoginRequest result = new ProtoMsg.LoginRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ProtoMsg.LoginRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.token_ = token_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsg.LoginRequest) {
          return mergeFrom((ProtoMsg.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoMsg.LoginRequest other) {
        if (other == ProtoMsg.LoginRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>int64 user_id = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:LoginRequest)
    private static final ProtoMsg.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoMsg.LoginRequest();
    }

    public static ProtoMsg.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
      @java.lang.Override
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoMsg.LoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *true 表示成功，false表示失败
     * </pre>
     *
     * <code>bool result = 1;</code>
     * @return The result.
     */
    boolean getResult();

    /**
     * <pre>
     *错误码
     * </pre>
     *
     * <code>uint32 code = 2;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     *错误描述
     * </pre>
     *
     * <code>string info = 3;</code>
     * @return The info.
     */
    java.lang.String getInfo();
    /**
     * <pre>
     *错误描述
     * </pre>
     *
     * <code>string info = 3;</code>
     * @return The bytes for info.
     */
    com.google.protobuf.ByteString
        getInfoBytes();

    /**
     * <pre>
     *错误描述是否提示给用户:1 提示;0 不提示
     * </pre>
     *
     * <code>uint32 expose = 4;</code>
     * @return The expose.
     */
    int getExpose();
  }
  /**
   * Protobuf type {@code LoginResponse}
   */
  public static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginResponse)
      LoginResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponse() {
      info_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsg.internal_static_LoginResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsg.internal_static_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoMsg.LoginResponse.class, ProtoMsg.LoginResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_ = false;
    /**
     * <pre>
     *true 表示成功，false表示失败
     * </pre>
     *
     * <code>bool result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public boolean getResult() {
      return result_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_ = 0;
    /**
     * <pre>
     *错误码
     * </pre>
     *
     * <code>uint32 code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int INFO_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object info_ = "";
    /**
     * <pre>
     *错误描述
     * </pre>
     *
     * <code>string info = 3;</code>
     * @return The info.
     */
    @java.lang.Override
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *错误描述
     * </pre>
     *
     * <code>string info = 3;</code>
     * @return The bytes for info.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPOSE_FIELD_NUMBER = 4;
    private int expose_ = 0;
    /**
     * <pre>
     *错误描述是否提示给用户:1 提示;0 不提示
     * </pre>
     *
     * <code>uint32 expose = 4;</code>
     * @return The expose.
     */
    @java.lang.Override
    public int getExpose() {
      return expose_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != false) {
        output.writeBool(1, result_);
      }
      if (code_ != 0) {
        output.writeUInt32(2, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(info_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, info_);
      }
      if (expose_ != 0) {
        output.writeUInt32(4, expose_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(info_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, info_);
      }
      if (expose_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, expose_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoMsg.LoginResponse)) {
        return super.equals(obj);
      }
      ProtoMsg.LoginResponse other = (ProtoMsg.LoginResponse) obj;

      if (getResult()
          != other.getResult()) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getInfo()
          .equals(other.getInfo())) return false;
      if (getExpose()
          != other.getExpose()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getResult());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
      hash = (37 * hash) + EXPOSE_FIELD_NUMBER;
      hash = (53 * hash) + getExpose();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoMsg.LoginResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.LoginResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMsg.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProtoMsg.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ProtoMsg.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoMsg.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMsg.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoMsg.LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginResponse)
        ProtoMsg.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsg.internal_static_LoginResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsg.internal_static_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoMsg.LoginResponse.class, ProtoMsg.LoginResponse.Builder.class);
      }

      // Construct using com.xzccc.netty_server.model.msg.ProtoMsg.LoginResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = false;
        code_ = 0;
        info_ = "";
        expose_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsg.internal_static_LoginResponse_descriptor;
      }

      @java.lang.Override
      public ProtoMsg.LoginResponse getDefaultInstanceForType() {
        return ProtoMsg.LoginResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoMsg.LoginResponse build() {
        ProtoMsg.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoMsg.LoginResponse buildPartial() {
        ProtoMsg.LoginResponse result = new ProtoMsg.LoginResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ProtoMsg.LoginResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.info_ = info_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.expose_ = expose_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsg.LoginResponse) {
          return mergeFrom((ProtoMsg.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoMsg.LoginResponse other) {
        if (other == ProtoMsg.LoginResponse.getDefaultInstance()) return this;
        if (other.getResult() != false) {
          setResult(other.getResult());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getInfo().isEmpty()) {
          info_ = other.info_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getExpose() != 0) {
          setExpose(other.getExpose());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                result_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                code_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                info_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                expose_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean result_ ;
      /**
       * <pre>
       *true 表示成功，false表示失败
       * </pre>
       *
       * <code>bool result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public boolean getResult() {
        return result_;
      }
      /**
       * <pre>
       *true 表示成功，false表示失败
       * </pre>
       *
       * <code>bool result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(boolean value) {

        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *true 表示成功，false表示失败
       * </pre>
       *
       * <code>bool result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = false;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       *错误码
       * </pre>
       *
       * <code>uint32 code = 2;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *错误码
       * </pre>
       *
       * <code>uint32 code = 2;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误码
       * </pre>
       *
       * <code>uint32 code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <pre>
       *错误描述
       * </pre>
       *
       * <code>string info = 3;</code>
       * @return The info.
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *错误描述
       * </pre>
       *
       * <code>string info = 3;</code>
       * @return The bytes for info.
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误描述
       * </pre>
       *
       * <code>string info = 3;</code>
       * @param value The info to set.
       * @return This builder for chaining.
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        info_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误描述
       * </pre>
       *
       * <code>string info = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInfo() {
        info_ = getDefaultInstance().getInfo();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误描述
       * </pre>
       *
       * <code>string info = 3;</code>
       * @param value The bytes for info to set.
       * @return This builder for chaining.
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        info_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int expose_ ;
      /**
       * <pre>
       *错误描述是否提示给用户:1 提示;0 不提示
       * </pre>
       *
       * <code>uint32 expose = 4;</code>
       * @return The expose.
       */
      @java.lang.Override
      public int getExpose() {
        return expose_;
      }
      /**
       * <pre>
       *错误描述是否提示给用户:1 提示;0 不提示
       * </pre>
       *
       * <code>uint32 expose = 4;</code>
       * @param value The expose to set.
       * @return This builder for chaining.
       */
      public Builder setExpose(int value) {

        expose_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误描述是否提示给用户:1 提示;0 不提示
       * </pre>
       *
       * <code>uint32 expose = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpose() {
        bitField0_ = (bitField0_ & ~0x00000008);
        expose_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:LoginResponse)
    private static final ProtoMsg.LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoMsg.LoginResponse();
    }

    public static ProtoMsg.LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
      @java.lang.Override
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoMsg.LoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.HeadType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.HeadType type = 1;</code>
     * @return The type.
     */
    ProtoMsg.HeadType getType();

    /**
     * <pre>
     *消息系列号
     * </pre>
     *
     * <code>uint64 sequence = 2;</code>
     * @return The sequence.
     */
    long getSequence();

    /**
     * <code>string session_id = 3;</code>
     * @return The sessionId.
     */
    java.lang.String getSessionId();
    /**
     * <code>string session_id = 3;</code>
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>optional .LoginRequest loginRequest = 4;</code>
     * @return Whether the loginRequest field is set.
     */
    boolean hasLoginRequest();
    /**
     * <code>optional .LoginRequest loginRequest = 4;</code>
     * @return The loginRequest.
     */
    ProtoMsg.LoginRequest getLoginRequest();
    /**
     * <code>optional .LoginRequest loginRequest = 4;</code>
     */
    ProtoMsg.LoginRequestOrBuilder getLoginRequestOrBuilder();

    /**
     * <code>optional .LoginResponse loginResponse = 5;</code>
     * @return Whether the loginResponse field is set.
     */
    boolean hasLoginResponse();
    /**
     * <code>optional .LoginResponse loginResponse = 5;</code>
     * @return The loginResponse.
     */
    ProtoMsg.LoginResponse getLoginResponse();
    /**
     * <code>optional .LoginResponse loginResponse = 5;</code>
     */
    ProtoMsg.LoginResponseOrBuilder getLoginResponseOrBuilder();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      sessionId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMsg.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMsg.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoMsg.Message.class, ProtoMsg.Message.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.HeadType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.HeadType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public ProtoMsg.HeadType getType() {
      ProtoMsg.HeadType result = ProtoMsg.HeadType.forNumber(type_);
      return result == null ? ProtoMsg.HeadType.UNRECOGNIZED : result;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 2;
    private long sequence_ = 0L;
    /**
     * <pre>
     *消息系列号
     * </pre>
     *
     * <code>uint64 sequence = 2;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public long getSequence() {
      return sequence_;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 3;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string session_id = 3;</code>
     * @return The bytes for sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGINREQUEST_FIELD_NUMBER = 4;
    private ProtoMsg.LoginRequest loginRequest_;
    /**
     * <code>optional .LoginRequest loginRequest = 4;</code>
     * @return Whether the loginRequest field is set.
     */
    @java.lang.Override
    public boolean hasLoginRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .LoginRequest loginRequest = 4;</code>
     * @return The loginRequest.
     */
    @java.lang.Override
    public ProtoMsg.LoginRequest getLoginRequest() {
      return loginRequest_ == null ? ProtoMsg.LoginRequest.getDefaultInstance() : loginRequest_;
    }
    /**
     * <code>optional .LoginRequest loginRequest = 4;</code>
     */
    @java.lang.Override
    public ProtoMsg.LoginRequestOrBuilder getLoginRequestOrBuilder() {
      return loginRequest_ == null ? ProtoMsg.LoginRequest.getDefaultInstance() : loginRequest_;
    }

    public static final int LOGINRESPONSE_FIELD_NUMBER = 5;
    private ProtoMsg.LoginResponse loginResponse_;
    /**
     * <code>optional .LoginResponse loginResponse = 5;</code>
     * @return Whether the loginResponse field is set.
     */
    @java.lang.Override
    public boolean hasLoginResponse() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .LoginResponse loginResponse = 5;</code>
     * @return The loginResponse.
     */
    @java.lang.Override
    public ProtoMsg.LoginResponse getLoginResponse() {
      return loginResponse_ == null ? ProtoMsg.LoginResponse.getDefaultInstance() : loginResponse_;
    }
    /**
     * <code>optional .LoginResponse loginResponse = 5;</code>
     */
    @java.lang.Override
    public ProtoMsg.LoginResponseOrBuilder getLoginResponseOrBuilder() {
      return loginResponse_ == null ? ProtoMsg.LoginResponse.getDefaultInstance() : loginResponse_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != ProtoMsg.HeadType.LOGIN_REQUEST.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (sequence_ != 0L) {
        output.writeUInt64(2, sequence_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getLoginRequest());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(5, getLoginResponse());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != ProtoMsg.HeadType.LOGIN_REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (sequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, sequence_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLoginRequest());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getLoginResponse());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoMsg.Message)) {
        return super.equals(obj);
      }
      ProtoMsg.Message other = (ProtoMsg.Message) obj;

      if (type_ != other.type_) return false;
      if (getSequence()
          != other.getSequence()) return false;
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (hasLoginRequest() != other.hasLoginRequest()) return false;
      if (hasLoginRequest()) {
        if (!getLoginRequest()
            .equals(other.getLoginRequest())) return false;
      }
      if (hasLoginResponse() != other.hasLoginResponse()) return false;
      if (hasLoginResponse()) {
        if (!getLoginResponse()
            .equals(other.getLoginResponse())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequence());
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      if (hasLoginRequest()) {
        hash = (37 * hash) + LOGINREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getLoginRequest().hashCode();
      }
      if (hasLoginResponse()) {
        hash = (37 * hash) + LOGINRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getLoginResponse().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoMsg.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMsg.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMsg.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMsg.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProtoMsg.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ProtoMsg.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoMsg.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMsg.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoMsg.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        ProtoMsg.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMsg.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMsg.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoMsg.Message.class, ProtoMsg.Message.Builder.class);
      }

      // Construct using com.xzccc.netty_server.model.msg.ProtoMsg.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLoginRequestFieldBuilder();
          getLoginResponseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        sequence_ = 0L;
        sessionId_ = "";
        loginRequest_ = null;
        if (loginRequestBuilder_ != null) {
          loginRequestBuilder_.dispose();
          loginRequestBuilder_ = null;
        }
        loginResponse_ = null;
        if (loginResponseBuilder_ != null) {
          loginResponseBuilder_.dispose();
          loginResponseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMsg.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public ProtoMsg.Message getDefaultInstanceForType() {
        return ProtoMsg.Message.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoMsg.Message build() {
        ProtoMsg.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoMsg.Message buildPartial() {
        ProtoMsg.Message result = new ProtoMsg.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ProtoMsg.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sequence_ = sequence_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sessionId_ = sessionId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.loginRequest_ = loginRequestBuilder_ == null
              ? loginRequest_
              : loginRequestBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.loginResponse_ = loginResponseBuilder_ == null
              ? loginResponse_
              : loginResponseBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMsg.Message) {
          return mergeFrom((ProtoMsg.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoMsg.Message other) {
        if (other == ProtoMsg.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSequence() != 0L) {
          setSequence(other.getSequence());
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasLoginRequest()) {
          mergeLoginRequest(other.getLoginRequest());
        }
        if (other.hasLoginResponse()) {
          mergeLoginResponse(other.getLoginResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                sequence_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                sessionId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getLoginRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getLoginResponseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.HeadType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.HeadType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.HeadType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public ProtoMsg.HeadType getType() {
        ProtoMsg.HeadType result = ProtoMsg.HeadType.forNumber(type_);
        return result == null ? ProtoMsg.HeadType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.HeadType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(ProtoMsg.HeadType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.HeadType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <pre>
       *消息系列号
       * </pre>
       *
       * <code>uint64 sequence = 2;</code>
       * @return The sequence.
       */
      @java.lang.Override
      public long getSequence() {
        return sequence_;
      }
      /**
       * <pre>
       *消息系列号
       * </pre>
       *
       * <code>uint64 sequence = 2;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(long value) {

        sequence_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息系列号
       * </pre>
       *
       * <code>uint64 sequence = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <code>string session_id = 3;</code>
       * @return The sessionId.
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string session_id = 3;</code>
       * @return The bytes for sessionId.
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string session_id = 3;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sessionId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string session_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        sessionId_ = getDefaultInstance().getSessionId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string session_id = 3;</code>
       * @param value The bytes for sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sessionId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private ProtoMsg.LoginRequest loginRequest_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoMsg.LoginRequest, ProtoMsg.LoginRequest.Builder, ProtoMsg.LoginRequestOrBuilder> loginRequestBuilder_;
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       * @return Whether the loginRequest field is set.
       */
      public boolean hasLoginRequest() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       * @return The loginRequest.
       */
      public ProtoMsg.LoginRequest getLoginRequest() {
        if (loginRequestBuilder_ == null) {
          return loginRequest_ == null ? ProtoMsg.LoginRequest.getDefaultInstance() : loginRequest_;
        } else {
          return loginRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       */
      public Builder setLoginRequest(ProtoMsg.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginRequest_ = value;
        } else {
          loginRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       */
      public Builder setLoginRequest(
          ProtoMsg.LoginRequest.Builder builderForValue) {
        if (loginRequestBuilder_ == null) {
          loginRequest_ = builderForValue.build();
        } else {
          loginRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       */
      public Builder mergeLoginRequest(ProtoMsg.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            loginRequest_ != null &&
            loginRequest_ != ProtoMsg.LoginRequest.getDefaultInstance()) {
            getLoginRequestBuilder().mergeFrom(value);
          } else {
            loginRequest_ = value;
          }
        } else {
          loginRequestBuilder_.mergeFrom(value);
        }
        if (loginRequest_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       */
      public Builder clearLoginRequest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        loginRequest_ = null;
        if (loginRequestBuilder_ != null) {
          loginRequestBuilder_.dispose();
          loginRequestBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       */
      public ProtoMsg.LoginRequest.Builder getLoginRequestBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getLoginRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       */
      public ProtoMsg.LoginRequestOrBuilder getLoginRequestOrBuilder() {
        if (loginRequestBuilder_ != null) {
          return loginRequestBuilder_.getMessageOrBuilder();
        } else {
          return loginRequest_ == null ?
              ProtoMsg.LoginRequest.getDefaultInstance() : loginRequest_;
        }
      }
      /**
       * <code>optional .LoginRequest loginRequest = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoMsg.LoginRequest, ProtoMsg.LoginRequest.Builder, ProtoMsg.LoginRequestOrBuilder>
          getLoginRequestFieldBuilder() {
        if (loginRequestBuilder_ == null) {
          loginRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoMsg.LoginRequest, ProtoMsg.LoginRequest.Builder, ProtoMsg.LoginRequestOrBuilder>(
                  getLoginRequest(),
                  getParentForChildren(),
                  isClean());
          loginRequest_ = null;
        }
        return loginRequestBuilder_;
      }

      private ProtoMsg.LoginResponse loginResponse_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoMsg.LoginResponse, ProtoMsg.LoginResponse.Builder, ProtoMsg.LoginResponseOrBuilder> loginResponseBuilder_;
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       * @return Whether the loginResponse field is set.
       */
      public boolean hasLoginResponse() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       * @return The loginResponse.
       */
      public ProtoMsg.LoginResponse getLoginResponse() {
        if (loginResponseBuilder_ == null) {
          return loginResponse_ == null ? ProtoMsg.LoginResponse.getDefaultInstance() : loginResponse_;
        } else {
          return loginResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       */
      public Builder setLoginResponse(ProtoMsg.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginResponse_ = value;
        } else {
          loginResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       */
      public Builder setLoginResponse(
          ProtoMsg.LoginResponse.Builder builderForValue) {
        if (loginResponseBuilder_ == null) {
          loginResponse_ = builderForValue.build();
        } else {
          loginResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       */
      public Builder mergeLoginResponse(ProtoMsg.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            loginResponse_ != null &&
            loginResponse_ != ProtoMsg.LoginResponse.getDefaultInstance()) {
            getLoginResponseBuilder().mergeFrom(value);
          } else {
            loginResponse_ = value;
          }
        } else {
          loginResponseBuilder_.mergeFrom(value);
        }
        if (loginResponse_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       */
      public Builder clearLoginResponse() {
        bitField0_ = (bitField0_ & ~0x00000010);
        loginResponse_ = null;
        if (loginResponseBuilder_ != null) {
          loginResponseBuilder_.dispose();
          loginResponseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       */
      public ProtoMsg.LoginResponse.Builder getLoginResponseBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getLoginResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       */
      public ProtoMsg.LoginResponseOrBuilder getLoginResponseOrBuilder() {
        if (loginResponseBuilder_ != null) {
          return loginResponseBuilder_.getMessageOrBuilder();
        } else {
          return loginResponse_ == null ?
              ProtoMsg.LoginResponse.getDefaultInstance() : loginResponse_;
        }
      }
      /**
       * <code>optional .LoginResponse loginResponse = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoMsg.LoginResponse, ProtoMsg.LoginResponse.Builder, ProtoMsg.LoginResponseOrBuilder>
          getLoginResponseFieldBuilder() {
        if (loginResponseBuilder_ == null) {
          loginResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoMsg.LoginResponse, ProtoMsg.LoginResponse.Builder, ProtoMsg.LoginResponseOrBuilder>(
                  getLoginResponse(),
                  getParentForChildren(),
                  isClean());
          loginResponse_ = null;
        }
        return loginResponseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final ProtoMsg.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoMsg.Message();
    }

    public static ProtoMsg.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoMsg.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\".\n\014LoginRequest\022\017\n\007user_" +
      "id\030\001 \001(\003\022\r\n\005token\030\002 \001(\t\"K\n\rLoginResponse" +
      "\022\016\n\006result\030\001 \001(\010\022\014\n\004code\030\002 \001(\r\022\014\n\004info\030\003" +
      " \001(\t\022\016\n\006expose\030\004 \001(\r\"\301\001\n\007Message\022\027\n\004type" +
      "\030\001 \001(\0162\t.HeadType\022\020\n\010sequence\030\002 \001(\004\022\022\n\ns" +
      "ession_id\030\003 \001(\t\022(\n\014loginRequest\030\004 \001(\0132\r." +
      "LoginRequestH\000\210\001\001\022*\n\rloginResponse\030\005 \001(\013" +
      "2\016.LoginResponseH\001\210\001\001B\017\n\r_loginRequestB\020" +
      "\n\016_loginResponse*\316\001\n\010HeadType\022\021\n\rLOGIN_R" +
      "EQUEST\020\000\022\022\n\016LOGIN_RESPONSE\020\001\022\022\n\016LOGOUT_R" +
      "EQUEST\020\002\022\023\n\017LOGOUT_RESPONSE\020\003\022\025\n\021KEEPALI" +
      "VE_REQUEST\020\004\022\026\n\022KEEPALIVE_RESPONSE\020\005\022\023\n\017" +
      "MESSAGE_REQUEST\020\006\022\024\n\020MESSAGE_RESPONSE\020\007\022" +
      "\030\n\024MESSAGE_NOTIFICATION\020\010B,\n com.xzccc.n" +
      "etty_server.model.msgB\010ProtoMsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "UserId", "Token", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "Result", "Code", "Info", "Expose", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Type", "Sequence", "SessionId", "LoginRequest", "LoginResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
