server:
  port: 8081
  websocket-port: 9090
  servlet:
    context-path: "/v1"

hash:
  salt: "g3e5o1t2g3n7e4m6k4k8h4v7l7g6n5z3"

jwt:
  secret: "xzcccim"
  exp: 30

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: "@Wsnidcl1"
    url: jdbc:mysql://localhost:3306/im?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
